services:
  safe_heaven_backend:
    container_name: safe_heaven_backend
    image: amdryzen7600x/safe_heaven_backend:latest
    env_file: "./compose.env"
    depends_on:
      - postgres
    ports:
      - 42069:3000

  safe_heaven_frontend:
    container_name: safe_heaven_frontend
    image: amdryzen7600x/safe_heaven_frontend:latest
    env_file: "./compose.env"
    depends_on:
      - safe_heaven_backend
    ports:
      - 6969:80

  postgres:
    container_name: postgres
    image: postgres:bullseye
    env_file: "./compose.env"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  data:

networks:
  network1:
    name: safe_heaven
    external: true
