services:
  safe_heaven_backend:
    container_name: safe_heaven_backend
    build: ../safe_heaven_backend
    env_file: "./compose.env"
    depends_on:
      - postgres
    ports:
      - 42069:3000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
      com.centurylinklabs.watchtower.enable: false

  safe_heaven_frontend:
    container_name: safe_heaven_frontend
    env_file: "./compose.env"
    build:
      context: ../safe_heaven_frontend
      dockerfile: ../safe_heaven_frontend/Dockerfile
      args:
        HOST: ${HOST}
        PORT: ${PORT}
    depends_on:
      - safe_heaven_backend
    ports:
      - 6969:80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
      com.centurylinklabs.watchtower.enable: false

  postgres:
    container_name: postgres
    image: postgres:bullseye
    env_file: "./compose.env"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    restart: unless-stopped
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
      com.centurylinklabs.watchtower.enable: false

volumes:
  data:

networks:
  network1:
    name: safe_heaven
    external: true
